### ISSUE TITLE
can make a demo like the basis cmd?

### ISSUE THREAD

**Issue by iamnewaplayer** [roy-t/SuperCompressedDotNet#1]
i need to make a basis file bytes with c#
like this function
basisu -y_flip -output_file unity_flipped.basis input.png
can i use this project do is?

**Comment by roy-t** [comment]
Hey, I'm not sure if Unity would be able to read the files generated by SuperCompressed. As the zip based compression is not well-defined in the standard. I would using SuperCompressed for both encoding and transcoding an image, like in the readme. Not for only one part. 

Also, unfortunately, SuperCompressed does not support y-flip, so you would have to y-flip your image yourself before encoding it. 

Does this answer your question? :)

**Comment by iamnewaplayer** [comment]
y-flip by my self is ok
unity can read the file by this cmd
basisu -y_flip -output_file unity_flipped.basis input.png
i don't know basisu.exe what to do...
i just know   in window unity read this unity_flipped.basis with bc7
in android and ios with astc_4x4

**Comment by roy-t** [comment]
If you create the file with SuperCompressed, as in the README you can read it in Unity by using the ZstdSharp library:

```
using ZstdSharp;
...
using var decompressor = new Decompressor();
var bytes = decompressor.Unwrap(texture);
 ```
 
 `bytes` then contains a valid basisu file that Unity should be able to read.

**Comment by iamnewaplayer** [comment]
i try it 
it work!!
tks!!

**Comment by iamnewaplayer** [comment]
why i use the do process the same file
the file size is bigger than basisu.exe ?
use the same source file  a.png  size 2kb
basisu.exe a.png  ---> 2kb
use the up function  ----> 6kb    close the MipMapGeneration   5kb

**Comment by roy-t** [comment]
For really small images there can be a large difference due to the extra information embedded. For larger images (like a couple of Megabytes) there should not be a large difference.
